name: Continuous Deployment to AWS 

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, closed, synchronize]

  workflow_dispatch:

permissions:
    id-token: write
    contents: read

jobs:
  deploy-dev:
    name: deploy to aws account
    runs-on: ubuntu-latest

    if: ${{ github.event_name == 'pull_request' && github.event.action != 'closed' || github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}

    steps:
      - name: checkout 
        uses: actions/checkout@v4

      - name: deploy to aws account
        uses: ./.github/actions/deploy
        with:
          aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
          environment: dev
          

